spring:
    application:
        name: parameter-catalog-rapizzas

    cloud:
        config:
            server:
                git:
                    uri: https://github.com/cristopherr26/Parameter-Catalog-Rapizzas
                    default-label: main
                    search-paths:
                        - Parameter-Catalog-Rapizzas

server:
    port: 2111
